version: "3.6"

services:
  static:
    container_name: "static"
    image: ghcr.io/kth-biblioteket/static:${REPO_TYPE}
    restart: "always"
    env_file:
      - static.env
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./.htpasswd:/etc/nginx/.htpasswd
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.static.rule=Host(`${DOMAIN_NAME}`)"
      - "traefik.http.routers.static.entrypoints=websecure"
      - "traefik.http.routers.static.tls=true"
      - "traefik.http.routers.static.tls.certresolver=myresolver"  
    networks:
      - "apps-net"

networks:
  apps-net:
    external: true